"""initial.

Revision ID: 1cbcb4f45d3f
Revises: 
Create Date: 2026-09-29 15:02:20.652790
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = '1cbcb4f45d3f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.String(length=64), nullable=False),
    sa.Column('title_plate', sa.String(length=120), nullable=False),
    sa.Column('description_plate', sa.Text(), nullable=False),
    sa.Column('image_edit_prompt', sa.Text(), nullable=False),
    sa.Column('master_selection_mode', sa.String(length=32), nullable=False),
    sa.Column('enhance_references', sa.Boolean(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('prompt_versions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('schema', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_name'), 'prompt_versions', ['name'], unique=False)
    op.create_table('artifacts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('object_key', sa.String(length=1024), nullable=False),
    sa.Column('source_artifact_id', sa.String(length=64), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('byte_size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_index(op.f('ix_artifacts_kind'), 'artifacts', ['kind'], unique=False)
    op.create_table('cost_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('operation', sa.String(length=128), nullable=False),
    sa.Column('units', sa.Float(), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_events_job_id'), 'cost_events', ['job_id'], unique=False)
    op.create_table('generations',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('stage_run_id', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('prompt_version', sa.String(length=64), nullable=True),
    sa.Column('prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('cost_estimate', sa.Float(), nullable=True),
    sa.Column('response_summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generations_job_id'), 'generations', ['job_id'], unique=False)
    op.create_table('stage_runs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('operation_key', sa.String(length=255), nullable=True),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('input_digest', sa.String(length=128), nullable=True),
    sa.Column('output_artifact_ids', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_runs_job_id'), 'stage_runs', ['job_id'], unique=False)
    op.create_index(op.f('ix_stage_runs_stage'), 'stage_runs', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stage_runs_stage'), table_name='stage_runs')
    op.drop_index(op.f('ix_stage_runs_job_id'), table_name='stage_runs')
    op.drop_table('stage_runs')
    op.drop_index(op.f('ix_generations_job_id'), table_name='generations')
    op.drop_table('generations')
    op.drop_index(op.f('ix_cost_events_job_id'), table_name='cost_events')
    op.drop_table('cost_events')
    op.drop_index(op.f('ix_artifacts_kind'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_prompt_versions_name'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
